# Generated by Django 5.0.7 on 2024-11-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0002_user_remove_workexperience_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
